- name: Deploy to App Script & Update Live Site
  run: |
    clasp push --force
    # 새로운 버전을 생성하고, 기존 배포 ID(-i)에 해당 버전을 즉시 적용합니다.
    clasp deploy -i AKfycbyTEOXemEy0q67fjn2yqxnNlxobfCD9yIf0hcrbF6jvy3q1YSevu5T8kGDiTX7qX9bWpw -d "GitHub Actions Auto Update"