- name: Deploy to App Script & Update Live Site
        id: deploy_step
        run: |
          clasp push --force
          clasp deploy -i AKfycbyTEOXemEy0q67fjn2yqxnNlxobfCD9yIf0hcrbF6jvy3q1YSevu5T8kGDiTX7qX9bWpw -d "GitHub Actions Auto Update"

      # 배포 실패 시에만 실행되는 단계
      - name: If Deploy Fails
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "🚨 GAS 배포 실패 경고!",
              body: "GitHub Actions에서 clasp deploy 중 오류가 발생했습니다. 로그를 확인해 주세요! 🕵️‍♂️"
            })